from typing import Dict, List
from src.utils.logger import get_logger

logger = get_logger("creative_agent")

class CreativeAgent:
    """
    Creates a clean human-readable marketing report 
    based on insights generated by InsightAgent.
    """

    def create_output(self, insights: Dict, plan: List[str]) -> str:
        if "error" in insights:
            return "Could not create creative output: " + insights.get("error", "")

        lines = []
        lines.append("EXECUTIVE SUMMARY")
        lines.append("------------------")
        lines.append(f"Total Spend: ${insights.get('total_spend'):,}")
        lines.append(f"Total Revenue: ${insights.get('total_revenue'):,}")
        lines.append(f"Total Purchases: {insights.get('total_purchases'):,}")
        lines.append(f"Average CTR: {insights.get('avg_ctr')}")
        lines.append(f"Average ROAS: {insights.get('avg_roas')}")
        lines.append("")
        lines.append(f"Top Performing Platform: {insights.get('best_platform')}")
        lines.append(f"Top Performing Country: {insights.get('best_country')}")
        lines.append(f"Best Creative Type: {insights.get('best_creative_type')}")
        lines.append(f"Best Audience Type: {insights.get('top_audience_type')}")
        lines.append(f"Best Adset: {insights.get('top_adset')}")
        lines.append("")
        lines.append(f"Highest Revenue Day: {insights.get('max_revenue_day')}")
        lines.append(f"Highest ROAS Day: {insights.get('max_roas_day')}")
        lines.append("")

        # --- Recommendations ---
        lines.append("RECOMMENDATIONS")
        lines.append("----------------")

        # 1. Top platform recommendation
        top_platform = insights.get("best_platform")
        lines.append(f"- Scale budget on **{top_platform}**, it has the highest purchase volume.")

        # 2. Creative type suggestion
        best_creative = insights.get("best_creative_type")
        lines.append(f"- Increase use of **{best_creative} creatives**, they give strongest ROAS.")

        # 3. Country scaling
        best_country = insights.get("best_country")
        lines.append(f"- Expand campaigns in **{best_country}**, it delivers strongest revenue.")

        # 4. Audience improvement
        audience = insights.get("top_audience_type")
        lines.append(f"- Allocate more budget to **{audience} audiences** (best returns).")

        # 5. Adset optimization
        adset = insights.get("top_adset")
        lines.append(f"- Use learnings from top adset **{adset}** to optimize weaker ones.")

        lines.append("")
        lines.append("PROJECT PLAN (Generated by Planner)")
        lines.append("------------------------------------")
        for step in plan:
            lines.append(f"- {step}")

        output = "\n".join(lines)
        logger.info("Creative output generated with updated fields.")
        return output
